### ISSUE TITLE
Discrepancy around LICENSE

### ISSUE THREAD

**Issue by lacabra** [team-asr/od-Data#3]
LICENSE file is for LGPLv2, but README links to GPLv3.

Please correct one or the other to resolve discrepancy around the license this repo uses.

Furthermore, if most of the contents of this repo is around data, I would highly encourage you to consider a more appropriate open license for data, instead of the software license you are currently chosen (or include both, one for the software components, and one for the data components). Follow this link for additional guidance on open data licenses:
https://opendefinition.org/licenses/

**Comment by gichangA** [comment]
We've updated the license. Thank you.
